language: scala

sudo: true

git:
  depth: 1

scala:
  - "2.11.8"

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install wget curl
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash 
  - export NVM_DIR="/home/travis/.nvm" 
  - sh $NVM_DIR/nvm.sh
  - nvm install 8.6.0 
  - nvm use 8.6.0 
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - curl https://sh.rustup.rs -sSf | sh
  - rustup update
  - rustup default stable

script:
  - cd ./otoroshi; sbt ";clean;compile;test;dist;assembly"
  - cd ../otoroshi/javascript; yarn install; yarn build
  - cd ../../manual; sbt ";clean;paradox"
  - cd ../clients/cli; cargo build --release

