language: scala

sudo: true

git:
  depth: 1

scala:
  - "2.11.8"

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install wget curl
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash 
  - export NVM_DIR="/home/travis/.nvm" 
  - sh $NVM_DIR/nvm.sh
  - nvm install 8.6.0 
  - nvm use 8.6.0 
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - wget --quiet https://sh.rustup.rs -O rustupinstall.sh
  - sh ./rustupinstall.sh -y
  - export PATH=$PATH:$HOME/.cargo/bin
  - rustup update
  - rustup default stable 

script:
  - echo $PWD
  - sh ./script/build.sh all

deploy:
  provider: script
  script: scripts/upload.sh
  on:
    branch: master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.nvm
    - $HOME/.yarn
    - $HOME/.yarn-cache
    - $HOME/.rustup
    - $HOME/.cargo

