---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis-master-deployment
  template:
    metadata:
      labels:
        component: redis-master-deployment
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-persistent-volume-claim
      containers:
        - name: redis
          image: redis
          # start redis in master mode with appendonly
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            # expose redis port
            - containerPort: 6379
              protocol: TCP
              name: "redis-port"
          volumeMounts:
            # map /data on the disk storage described above
            - name: redis-storage
              mountPath: /data
              # subPath: redis
---
# expose the redis deployment on a cluster internal (ClusterIP) ip address
apiVersion: v1
kind: Service
metadata:
  name: redis-master-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis-master-deployment
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-port