---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistent-volume-claim-slaves
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# The deployment part, just deploy a redis server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: redis-slave-deployment
  template:
    metadata:
      labels:
        component: redis-slave-deployment
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-persistent-volume-claim-slave
      containers:
        - name: redis
          image: redis
          # start redis in slave mode
          command: ["redis-server", "--appendonly", "yes", "--slaveof", "redis-master-cluster-ip-service", "6379"]
          # expose redis port
          ports:
            - containerPort: 6379
              protocol: TCP
              name: "redis-port"
          # map /data on the disk storage described above
          volumeMounts:
            - name: redis-storage
              mountPath: /data
              # subPath: redis
---
# expose the redis deployment on a cluster internal (ClusterIP) ip address
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis-slave-deployment
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-port