version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
    - 9200:9200
    environment:
    - "xpack.security.enabled=false"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"