version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
    - 9200:9200
    environment:
    - "xpack.security.enabled=false"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      docker-elk:

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
    - 5601:5601
    environment:
    - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
    - docker-elk
    depends_on:
    - elasticsearch
networks:
  docker-elk:
    driver: bridge