---
apiVersion: proxy.otoroshi.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.service.name }}-certificate
spec:
  description: "certificate for {{ .Values.service.name }}"
  autoRenew: true
  csr:
    issuer: CN=Otoroshi Root
    hosts: 
    - {{ .Values.service.name }}
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Values.service.apiName }}.{{ .Release.Namespace }}.svc.cluster.local
    - otoroshi.{{ .Values.env.domain }}
    - otoroshi-api.{{ .Values.env.domain }}
    - privateapps.{{ .Values.env.domain }}
    key:
      algo: rsa
      size: 2048
    subject: uid=otoroshi-service-cert, O=Otoroshi
    client: false
    ca: false
    duration: 31536000000
    signatureAlg: SHA256WithRSAEncryption
    digestAlg: SHA-256