---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: service-groups.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  #validation:
  #  openAPIV3Schema:
  #    type: object
  #    properties:
  #      spec:
  #        type: object
  #        properties:
  #          name:
  #            type: string
  #          description:
  #            type: string
  #          metadata:
  #            type: object
  names:
    kind: ServiceGroup
    plural: service-groups
    singular: service-group
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: organizations.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: Organization
    plural: organizations
    singular: organization
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: teams.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: Team
    plural: teams
    singular: team
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: service-descriptors.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  #validation:
  #  openAPIV3Schema:
  #    type: object
  #    properties:
  #      spec:
  #        type: object
  #        properties:
  #          group:
  #            type: string
  #          name:
  #            type: string
  #          env:
  #            type: string
  #          domain:
  #            type: string
  #          subdomain:
  #            type: string
  #          root:
  #            type: string
  #          matchingRoot:
  #            type: string
  #          stripPath:
  #            type: boolean
  #          enabled:
  #            type: boolean
  #          userFacing:
  #            type: boolean
  #          privateApp:
  #            type: boolean
  #          forceHttps:
  #            type: boolean
  #          maintenanceMode:
  #            type: boolean
  #          buildMode:
  #            type: boolean
  #          strictlyPrivate:
  #            type: boolean
  #          sendOtoroshiHeadersBack:
  #            type: boolean
  #          readOnly:
  #            type: boolean
  #          xForwardedHeaders:
  #            type: boolean
  #          overrideHost:
  #            type: boolean
  #          allowHttp10:
  #            type: boolean
  #          logAnalyticsOnServer:
  #            type: boolean
  #          useAkkaHttpClient:
  #            type: boolean
  #          useNewWSClient:
  #            type: boolean
  #          tcpUdpTunneling:
  #            type: boolean
  #          detectApiKeySooner:
  #            type: boolean
  #          letsEncrypt:
  #            type: boolean
  #          enforceSecureCommunication:
  #            type: boolean
  #          sendInfoToken:
  #            type: boolean
  #          sendStateChallenge:
  #            type: boolean
  #          securityExcludedPatterns:
  #            type: array
  #          publicPatterns:
  #            type: array
  #          privatePatterns:
  #            type: array
  #          additionalHeaders:
  #            type: object
  #          additionalHeadersOut:
  #            type: object
  #          missingOnlyHeadersIn:
  #            type: object
  #          missingOnlyHeadersOut:
  #            type: object
  #          removeHeadersIn:
  #            type: array
  #          removeHeadersOut:
  #            type: array
  #          headersVerification:
  #            type: object
  #          matchingHeaders:
  #            type: object
  #          metadata:
  #            type: object
  #          hosts:
  #            type: array
  #          paths:
  #            type: array
  #          issueCert:
  #            type: boolean
  #          issueCertCA:
  #            type: string
  names:
    kind: ServiceDescriptor
    plural: service-descriptors
    singular: service-descriptor
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apikeys.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  #validation:
  #  openAPIV3Schema:
  #    type: object
  #    properties:
  #      spec:
  #        type: object
  #        properties:
  #          daikokuToken:
  #            type: string
  #          secretName: 
  #            type: string
  #          exportSecret:
  #            type: boolean
  #          clientId:
  #            type: string
  #          clientSecret:
  #            type: string
  #          clientName:
  #            type: string
  #          authorizedEntities:
  #            type: array
  #          group:
  #            type: string
  #          enabled:
  #            type: boolean
  #          readOnly:
  #            type: boolean
  #          allowClientIdOnly:
  #            type: boolean
  #          throttlingQuota:
  #            type: integer
  #            format: int64
  #          dailyQuota:
  #            type: integer
  #            format: int64
  #          monthlyQuota:
  #            type: integer
  #            format: int64
  #          constrainedServicesOnly:
  #            type: boolean
  #          validUntil:
  #            type: integer
  #            format: int64
  #          tags:
  #            type: array
  #          metadata:
  #            type: object
  names:
    kind: ApiKey
    plural: apikeys
    singular: apikey
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  #validation:
  #  openAPIV3Schema:
  #    type: object
  #    properties:
  #      spec:
  #        type: object
  #        required: ["csr"]
  #        properties:
  #          name:
  #            type: string
  #          description:
  #            type: string
  #          secretName: 
  #            type: string
  #          exportSecret:
  #            type: boolean
  #          selfSigned:
  #            type: boolean
  #          ca:
  #            type: boolean
  #          autoRenew:
  #            type: boolean
  #          letsEncrypt:
  #            type: boolean
  #          client:
  #            type: boolean
  #          entityMetadata:
  #            type: object
  #          csr:
  #            type: object
  names:
    kind: Certificate
    plural: certificates
    singular: certificate
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: global-configs.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: GlobalConfig
    plural: global-configs
    singular: global-config
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jwt-verifiers.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: JwtVerifier
    plural: jwt-verifiers
    singular: jwt-verifier
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: auth-modules.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: AuthModule
    plural: auth-modules
    singular: auth-module
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scripts.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  #validation:
  #  openAPIV3Schema:
  #    type: object
  #    properties:
  #      spec:
  #        type: object
  #        required: ["code", "type"]
  #        properties:
  #          name:
  #            type: string
  #          desc:
  #            type: string
  #          code:
  #            type: string
  #          type:
  #            type: string
  #          metadata:
  #            type: object
  names:
    kind: Script
    plural: scripts
    singular: script
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tcp-services.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: TcpService
    plural: tcp-services
    singular: tcp-service
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: data-exporters.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: DataExporter
    plural: data-exporters
    singular: data-exporter
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: admins.proxy.otoroshi.io
spec:
  group: proxy.otoroshi.io
  version: v1alpha1
  preserveUnknownFields: true
  names:
    kind: Admin
    plural: admins
    singular: admin
  scope: Namespaced