version: '3'
services:

  client:
    build: ./client
    networks:
      - bench
    depends_on:
      - otoroshi

  otoroshi:
    build: ./otoroshi
    ports:
      - 8091:8091
    networks:
      - bench
    depends_on:
      - backend

  otoroshigraalvm:
    build: ./otoroshi-graalvm
    ports:
      - 8092:8092
    networks:
      - bench
    depends_on:
      - backend

  backend:
    build: ./backend
    networks:
      - bench
    ports:
      - 1026:1026

networks:
  bench:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24